---
title: "Rworksheet_Aguirre#2"
author: "Ryza Faith"
date: "2024-09-26"
output: html_document
---
1.
```{r}
sequence <- -5:5
print(sequence)
```
2.
```{r}
x <- 1:7
print(x)
```

3.
```{r}
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
print(ages[3])
print(ages[c(2, 4)])
print(ages[-c(4, 12)])
```
4.
```{r}
x <- c("first" = 3, "second" = 0, "third" = 9)
print(x)
print(x[c("first", "third")])
```
5.
```{r}
x <- -3:2
x[2] <- 0
print(x)
```
6A.
```{r}
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.5, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)
```

```{r}
diesel_data <- data.frame(month, price_per_liter, purchase_quantity)
print(diesel_data)
```
6B
```{r}
avg_expenditure <- weighted.mean(price_per_liter, purchase_quantity)
print(avg_expenditure)
```
7A.
```{r}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)
```
8A.
```{r}
power_ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrity_name <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods","Steven Spielberg", "Howard Stern", "50 Cent","Cast of the Sopranos", "Dan Brown", "Bruce Springsteen","Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas","Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling","Brad Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno","Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
print(power_ranking)
print(celebrity_name)
print(pay)
```
8B.
```{r}
power_ranking[which(celebrity_name == "J.K. Rowling")] <- 15
pay[which(celebrity_name == "J.K. Rowling")] <- 90
print(power_ranking)
print(pay)
```
8C.
```{r}
celebrity_data <- data.frame(PowerRanking = power_ranking, CelebrityName = celebrity_name, Pay = pay)
write.csv(celebrity_data, "PowerRanking.csv", row.names = FALSE)
imported_data <- read.csv("PowerRanking.csv")
print(imported_data)
```
8D.
```{r}
subset_data <- imported_data[10:20, ]
save(subset_data, file = "Ranks.RData")
print(subset_data)
save(subset_data, file = "Ranks.RData")
print(subset_data)
```
9A.
```{r}
options(repos = c(CRAN = "https://cran.rstudio.com/"))
install.packages("readxl")
library(readxl)
hotel_data <- read_excel("~/RWorksheet_Aguirre#2/hotels-vienna.xlsx")
hotel_data
```
9B.
```{r}
dataset_dimensions <- dim(hotel_data)
dataset_dimensions
```
9C.
```{r}
selected_columns <- hotel_data[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
selected_columns

```

```{r}
save(selected_columns, file = "new.RData")
```

```{r}

load("new.RData")
head(selected_columns)
tail(selected_columns)

```

```{r}
vegetables <- c("Carrot", "Broccoli", "Spinach", "Tomato", "Potato","Cabbage", "Cauliflower", "Pepper", "Cucumber", "Lettuce")
```

```{r}
vegetables <- c(vegetables, "Onion", "Garlic")
print(vegetables)
```


```{r}
vegetables <- c(vegetables[1:5], "Eggplant", "Zucchini", "Pumpkin", "Beetroot", vegetables[6:length(vegetables)])
print(vegetables)
length(vegetables)

```

```{r}
vegetables <- vegetables[-c(5, 10, 15)]
print(vegetables)
length(vegetables)

```

