---
title: "RWorksheeet_Aguirre#1"
author: "Ryza Faith"
date: "2024-09-20"
output: pdf_document
---
1.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41)
age
```

1a.
```{r}
length(age)

```
2.
```{r}
reciprocal_age <- 1 / age
reciprocal_age

```
3.
```{r}

new_age <- c(age, 0, age)
new_age
```

4.
```{r}

sorted_age <- sort(age)
sorted_age
```
5.
```{r}

min_age <- min(age)
max_age <- max(age)

min_age
max_age
```
6a.
```{r}

data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)

length(data)
```

7.
```{r}

doubled_data <- data * 2
doubled_data
```
8.1
```{r}

seq_1_to_100 <- seq(1, 100)
seq_1_to_100

```
8.2
```{r}

seq_20_to_60 <- seq(20, 60)
seq_20_to_60
```
8.3
```{r}
mean_20_to_60 <- mean(seq_20_to_60)
mean_20_to_60
```
8.4
```{r}
sum_51_to_91 <- sum(seq(51, 91))
sum_51_to_91
```
8.5
```{r}
seq(1,1000)
```
9.
```{r}

filtered_integers <- Filter(function(i) { all(i %% c(3, 5, 7) != 0) }, seq(100))
filtered_integers
```
10.
```{r}

seq_backwards <- seq(100, 1)
seq_backwards

```
11.
```{r}
multiples <- which(seq(1, 24) %% 3 == 0 | seq(1, 24) %% 5 == 0)
multiples
length(multiples)
```
11.
```{r}
sum_multiples <- sum(multiples)
sum_multiples

```
12.
x <- {0 + x + 5 + }
Descripe the output. 
The {} curly braces are used to create a code block in R, typically for grouping multiple expressions. However, the line is incomplete because it ends with +, an operator without a value or expression following it. R expects something to add to 5, so it will throw a syntax error.

13.
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
score[2]
score[3]

```
14a.
```{r}
a <- c(1, 2, NA, 4, NA, 6, 7)
print(a, na.print="-999")
```
14b.
```{r}
name <- readline(prompt="Input your name: ")
age <- readline(prompt="Input your age: ")
print(paste("My name is", name, "and I am", age, "years old."))
print(R.version.string)
```


